version: '3.8'
services:
  api:
    build: .
    container_name: blk-hacking-ind-shubham-kondekar
    ports:
      - "5477:5477"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: [ "gunicorn", "app.main:app", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:5477", "--reload" ]
  celery:
    build: .
    command: celery -A app.tasks.celery_app.celery worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
